build:
  cuda_version: "12.1.1"
  python_packages:
    - "accelerate==0.33.0"
    - "torch==2.4.0"
    - "transformers==4.44.0"
    - "diffusers==0.30.0"
    - "sentencepiece==0.2.0"
    - "protobuf==5.27.3"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.27.1"
    - "peft==0.12.0"
